### ISSUE TITLE
cant import this project in eclipse 

### ISSUE THREAD

**Issue by Android-Rocks** [simbiose/Encryption#1]
dear developer ,
you work is good. but i cant import this project in my eclipse .and also tell me how to encrypt my string url in android project.

**Comment by ademar111190** [comment]
Just an update, the version 1.1.0+ is basead in AES algorithm and not more in DES.

And about eclipse users, you can download the last version of library in sources.jar format and use on your eclipse project, [here the download link.](http://search.maven.org/#search|gav|1|g%3A%22se.simbio.encryption%22%20AND%20a%3A%22library%22)

**Comment by Android-Rocks** [comment]
thanks Dear
