### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by Floppe** [simbiose/Encryption#11]
Readme says lesser GPL but the license file is general GPL.

**Comment by ademar111190** [comment]
Thank you. I'll fix it as soon as possible, the correct license is LGPL.

I also want to change the license to MIT but I don't know if it is possible.

**Comment by metaphore** [comment]
@ademar111190 MIT license would be just awesome, hope you still haven't changed your mind about it.

**Comment by mdumrauf** [comment]
@ademar111190 any news on the license change?

**Comment by ademar111190** [comment]
I'll ask to the others contributors of the project if they agree once they also committed some code, if there is no problem to then I'll change the license as soon as possible.

**Comment by ademar111190** [comment]
I am very happy to announce that Encryption is now under the MIT license :)
