### ISSUE TITLE
How can we use it with file password protected ?

### ISSUE THREAD

**Issue by shree007** [simbiose/Encryption#13]
As we know that we can encrypt and decrypt the String , instead of  string i want to use it with file password protected. How may I do that?

**Comment by ademar111190** [comment]
Hi @shree007 

I don't know how files are written in disk, so I don't know how to protected then properly with encryption. As far as the library is under java we have a more complex problem once the file system can be very different depending on which OS is running.

I recommend to look up to a specific file encryption library, I think it is better than some workaround to use this library. Or if you want to add this functionally to this library you are very welcome. 😄
