### ISSUE TITLE
How decrypt in php?

### ISSUE THREAD

**Issue by Nazza97** [simbiose/Encryption#14]
I have saved password in database mysql and now i want login via web browser.. how to decrypt?

**Comment by ademar111190** [comment]
Hello @Nazza97 

You need to use the same algorithm and arguments in your PHP code as you used with encryption library. If you use the library defaults you need to use the default algorithm and the default arguments (the code of library defaults: [https://github.com/simbiose/Encryption/blob/master/Encryption/main/se/simbio/encryption/Encryption.java#L321](https://github.com/simbiose/Encryption/blob/master/Encryption/main/se/simbio/encryption/Encryption.java#L321))

I don't know anything about PHP so I can't help you with libraries or configurations in PHP, all I can say is if you use the same arguments and the same algorithm it will work.
