### ISSUE TITLE
maven can't  download this source

### ISSUE THREAD

**Issue by ELLIEbleu** [simbiose/Encryption#18]
I want to use this into  my project ,I use maven , so I add  encrytion's dependecy ,but maven can't  download  source . Do you know how to solve this problem?

**Comment by ademar111190** [comment]
Have you added jitpack? `maven { url 'https://jitpack.io' }`

**Comment by ELLIEbleu** [comment]
@ademar111190  sorry， There was a long time without looking at the issue . thank you reply . I added jitpack，but  when i use " Encryption.getDefault() " ,occurred  cannot resolve symbol 'Encryption'.
I don't know why cause this problem.

**Comment by ademar111190** [comment]
It is really strange.

Can you share a sample project with this error occurring?

**Comment by ELLIEbleu** [comment]
@ademar111190 
![pic](https://user-images.githubusercontent.com/13954035/28451797-13f28186-6e22-11e7-84cf-f2aec039e747.PNG)    
maven 's dependencies  exists  mistake with red color
so  in my project ,I use Encryption.getDefault() .I think Encrytion dependencies are not pull from origin  server. but i‘am not sure this cause.

**Comment by ademar111190** [comment]
yes it is strange. 

To me be able to help you I need you share with me a project where the error is happening.

**Comment by ELLIEbleu** [comment]
my project is sample . in main.class  ,I use  " Encryption.getDefault()"  ,I added   
 <repositories>
    <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
     </repository>
  </repositories>
 <dependency>
     <groupId>com.github.simbiose</groupId>
      <artifactId>Encryption</artifactId>
      <version>2.0.0</version>
 </dependency>
you can try to write this code in your ideal .

**Comment by ademar111190** [comment]
I tried but here it works.

Can you try to run the attached project?

[EncryptionIssue18.zip](https://github.com/simbiose/Encryption/files/1170455/EncryptionIssue18.zip)

**Comment by ELLIEbleu** [comment]
@ademar111190  I use compile software named 'intellij idea ' . but your project is android. I cannot  run this 
project . could you please offer me another project with java

**Comment by ademar111190** [comment]
@ELLIEbleu  [issue18.zip](https://github.com/simbiose/Encryption/files/1173506/issue18.zip)

**Comment by ademar111190** [comment]
Closing the issue as it seems to be solved, if not, let me now and I reopen the issue.
