### ISSUE TITLE
Please Help!!!

### ISSUE THREAD

**Issue by venky1995** [simbiose/Encryption#22]
....

**Comment by ademar111190** [comment]
Hi @venky1995 , can you share an example where the error is happening?

**Comment by ademar111190** [comment]
Hi @venky1995 , can you share an example where the error is happening?

**Comment by venky1995** [comment]
> Hi @venky1995 , can you share an example where the error is happening?
Hello sir, The decry-pt code generated successfully here no issues with it. The Project code i am using Decrypt code is this Link: https://github.com/beigirad/EncryptedGsonConverter  in this project after adding 80+ lines of json data and output is in simple List view with simple set adapter!  but unfortunately it showing the error when adding large json list. (with simple json its working great like 30-80 lines.)
http://topcrickethighlights.com/test/encrypt.json
http://topcrickethighlights.com/test/decrypt.json
Working Image Link with below 80+ lines of json: http://prntscr.com/l6kkzc
Error Image Link with above 80+lines of json: http://prntscr.com/l6kkse

**Comment by ademar111190** [comment]
I'm closing the issue, feel free to reopen if you have useful information to help me to help you.
